### ISSUE TITLE
Scalar type hints / double and float

### ISSUE THREAD

**Issue by UFOMelkor** [memio/model#10]
Hey,

I would like to add support for scalar type hints for PHP 7.0.
While implementing this feature I recognized that `float` as type is not handled in [`Memio\Model\Type`](https://github.com/memio/model/blob/v1.4.1/src/Memio/Model/Type.php#L39) (neither normalized with `double` nor mentioned within `$nonObjectTypes`.

Would you prefer to
- normalize `float` to `double`
- normalize `double` to `float`
- allow both types to be added

?

**Comment by gnugat** [comment]
Hey! I'd rather have `double` normalized to `float`, if you don't mind.
