### ISSUE TITLE
Object - is a 'soft reserved word' since php7

### ISSUE THREAD

**Issue by 3DFace** [memio/model#12]
Memio\Model\Object class name conflicts with ['List of other reserved words'](http://php.net/manual/en/reserved.other-reserved-words.php) from php documentation.
PhpStorm highlights it as error with message "Classes with names int, string, float, and bool as well as resource, object, mixed, and numeric are forbidden in PHP 7."

**Comment by gnugat** [comment]
Thank you for reporting this. So it currently works on PHP 7.0, but there's a possibility it might break in PHP 7.1, or 7.2, or any future version...

I'll try to come up with an alternative name and release a new major version (v2), due to the bacward compatibility break.

**Comment by gnugat** [comment]
Fixed by @roukmoute
