### ISSUE TITLE
The method "make" of ParameterTag should be static

### ISSUE THREAD

**Issue by oscarotero** [memio/model#3]
On create a parameterTag in this way:

``` php
$tag = ParameterTag::make();
```

A php warning is generated: 

> PHP Deprecated:  Non-static method Memio\Model\Phpdoc\ParameterTag::make() should not be called statically, assuming $this from incompatible context in ...

Here: https://github.com/memio/model/blob/master/src/Memio/Model/Phpdoc/ParameterTag.php#L59

**Comment by gnugat** [comment]
Good catch! I'll fix it during the day and tag it as version `1.3.2`. Thanks for reporting it

**Comment by oscarotero** [comment]
you're welcome. thank you for this great library

**Comment by gnugat** [comment]
I'm glad you like it :) . Should be fixed now.
