### ISSUE TITLE
Autocompletion for Object in PHPStorm

### ISSUE THREAD

**Issue by temp** [memio/model#5]
Anyone else got the problem that PHPStorm does not autocomplete Memio\Model\Object?
All other model classes work fine.
Maybe PHPStorm is confused by "Object"?

**Comment by temp** [comment]
Ok, I can confirm this, PHPStorm has a problem with the @return Object.
When I change it to @return $this or @return self, it works fine.
If noone objects, I would create a PR which changes the @return type hints of all models to $this.

**Comment by gnugat** [comment]
I don't see any issue with that, but I'm not sure which one to choose: `$this` or `self`?
Maybe the second one, since it can be found in [PHPdoc's documentation](http://phpdoc.org/docs/latest/references/phpdoc/tags/return.html)?

**Comment by temp** [comment]
I chose self, works fine!

**Comment by gnugat** [comment]
Released in [v1.3.5](https://github.com/memio/model/releases/tag/v1.3.5), thanks again!
